apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: k8s-lab
type: Opaque
stringData:
  POSTGRES_USER: k8s_lab_user
  POSTGRES_PASSWORD: REPLACE_WITH_LOCAL_DB_PASSWORD
  DB_USER: k8s_lab_user
  DB_PASSWORD: REPLACE_WITH_LOCAL_DB_PASSWORD
